name: Integration Tests
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop ]
 
jobs:
  build:
 
    runs-on: macos-latest
 
    steps:
    - uses: actions/checkout@v2
     
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
     
    - name: Build and Test
      run: xcodebuild clean build test -project ProdCast.xcodeproj -scheme "ProdCast" -destination 'platform=iOS Simulator,name=iPhone 12' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
